### ISSUE TITLE
@vercel/ncc Support

### ISSUE THREAD

**Issue by medz** [prisma/nexus-prisma#109]
#### Screenshot

![image](https://user-images.githubusercontent.com/5564821/130318987-b9a61b20-b759-4f96-9ba7-7e487595a235.png)
![image](https://user-images.githubusercontent.com/5564821/130320792-8af39b85-0d68-4968-9752-f62007c0a6c9.png)

#### Description 

After using `@vercel/ncc` + fastify to package and copy the packaged content to other places (such as Docker image), there will be a pre-dependency error when running.

NCC copy fastify package.json file code: https://github.com/fastify/fastify/blob/3956e684247492bff41bae30eed4355bfb0ef63d/fastify.js#L687

**AND**
After NCC is packaged, copy the packaged content separately and cannot run

#### Repro Steps/Link 

see https://github.com/odroe/socfony

**Comment by medz** [comment]
This is my temporary solution in the program: https://github.com/odroe/socfony/blob/main/Dockerfile#L12

**Comment by medz** [comment]
Sorry, https://github.com/prisma/nexus-prisma/blob/main/src/lib/peerDepValidator.ts#L20

**Comment by medz** [comment]
@prisma/client Supported ncc

**Comment by jasonkuhrt** [comment]
I've tried to repro this but failed. Can you help? I've invited you to https://github.com/prisma/repro-nexus-prisma-109 with write permissions.

**Comment by medz** [comment]
> I've tried to repro this but failed. Can you help? I've invited you to https://github.com/prisma/repro-nexus-prisma-109 with write permissions.

Yes, just move dist to a directory other than the project and run it to generate an error. This conflicts with the purpose of ncc packaging. The purpose of moving dist is to no longer download npm packages.

More see: https://github.com/prisma/repro-nexus-prisma-109/issues/1

**Comment by jasonkuhrt** [comment]
I see this error:

<img width="1455" alt="CleanShot 2021-08-24 at 12 55 55@2x" src="https://user-images.githubusercontent.com/284476/130658188-087dde5e-d2de-46b5-b46a-fe2645b30e9e.png">

**Comment by jasonkuhrt** [comment]
This comes from https://github.com/prisma/nexus-prisma/blob/74da7c236407e2cd1c9692dc544bae19728ba609/src/lib/peerDepValidator.ts#L99

The issue is that the peer dep validator should be disabled after bundling.

**Comment by jasonkuhrt** [comment]
I disabled the check and get to a lower level error, what the OP is about:

<img width="979" alt="CleanShot 2021-08-24 at 12 58 19@2x" src="https://user-images.githubusercontent.com/284476/130658536-f2ed9904-5ad2-41db-a822-f1888de0058c.png">

**Comment by jasonkuhrt** [comment]
@medz I understand that the issue is roughly this LOC https://github.com/prisma/nexus-prisma/blob/74da7c236407e2cd1c9692dc544bae19728ba609/src/helpers/prisma.ts#L17 however I still do not know what a solution could be.

The fact is prisma client import ID is dynamic.

How do we deal with that?

**Comment by jasonkuhrt** [comment]
I have an idea, it is less dynamic than I'm making it out to be. It is dynamic only at generation time.

I believe we can fix this issue by generating static code for the import ID.

Here's an example of what gets generated currently:

<img width="900" alt="CleanShot 2021-08-24 at 13 16 30@2x" src="https://user-images.githubusercontent.com/284476/130660815-0cda06e6-82a7-4e9c-baae-b8a0bef7125e.png">

The information is already statically there, but not in a way that will get rewritten by ncc yet.

**Comment by jasonkuhrt** [comment]
Here is a solution I prototyped on the generated source code and works with ncc. It is a minor change. It moves the require statement out of static library code and into generated library code. This allows for producing a static require for ncc.

![CleanShot 2021-08-24 at 13 29 50@2x](https://user-images.githubusercontent.com/284476/130662567-c3e10cd8-f962-48a8-bfc8-dd663ff9dffd.png)

**Comment by jasonkuhrt** [comment]
I've captured a failing test case here https://github.com/prisma/nexus-prisma/pull/113.
