### ISSUE TITLE
Issue deploying to Vercel

### ISSUE THREAD

**Issue by miguelbogota** [prisma/nexus-prisma#125]
#### Screenshot
<img width="1008" alt="Screen Shot 2021-08-27 at 8 38 19 AM" src="https://user-images.githubusercontent.com/49841013/131136097-04df32d6-cb65-430f-9fc3-04c500b179a8.png">

#### Description 
I recently switched from using Nexus to using Nexus Prisma plugin, but now the Vercel pipeline does not work correctly. The pipeline I had before was to following:

<img width="500" alt="Screen Shot 2021-08-27 at 8 41 50 AM" src="https://user-images.githubusercontent.com/49841013/131136593-0c6b61e0-535a-40a5-b9ec-d1e8327c7089.png">

Where it would install all the dependencies and then push the db config to the db. This was working correctly before, but after switching to Nexus Prisma plugin the pipeline break in the `npx prisma db push` (First screenshot), I changed the pipeline back to only `npm install` and this worked but I still need the `npx prisma db push` for future changes in the db.

#### Repro Steps/Link 

https://github.com/miguelbogota/pondshive

##### Dependencies:
```json
{
  "@prisma/client": "^2.27.0",
  "nexus": "^1.1.0",
  "nexus-prisma": "^0.30.0",
  "prisma": "^2.27.0",
}
```

**Comment by jasonkuhrt** [comment]
Why is `nexus-prisma` bin not found? Can you try the latest version of these deps (you're a few versions behind on prisma and nexus-prisma).

**Comment by miguelbogota** [comment]
Yes, I tried with a newer version and it worked. Thank you.

**Comment by jasonkuhrt** [comment]
@miguelbogota That's great to hear. Thanks for confirming!
