### ISSUE TITLE
jest doesn't find scalars

### ISSUE THREAD

**Issue by Manubi** [prisma/nexus-prisma#137]
<img width="878" alt="CleanShot 2021-08-30 at 23 18 20@2x" src="https://user-images.githubusercontent.com/20935138/131406981-94f8a052-2479-4072-8faf-e12a9117e8b2.png">

Hi,

"nexus-prisma": "^0.33.0",
 "nexus": "^1.1.0",
 "@prisma/client": "^2.30.1"
 "prisma": "^2.30.1"

thanks!

**Comment by jasonkuhrt** [comment]
Is this happening for you outside of Jest too?

**Comment by Manubi** [comment]
No, just if I run jest. I know it's not a nexus-prisma bug, but I think the chances of finding a solution are bigger here? :)

**Comment by jasonkuhrt** [comment]
Yeah it might be an integration issue that we can better support (Like we did for `vercel/ncc`) or at least document.

This is weird.

One thing I can say is that we're using the new Node's recent support for package exports field. I think only supported since Node 12.

I wonder if Jest transpilation/pre-processing is somehow failing on this...

Are all your deps up to date? 
Node 16 or 14?
Are you using ts-jest?
What does your jest config look like?

If all your deps are not up to date I would start there. And use Node 16 or 14 if 16 not possible for you.

**Comment by Manubi** [comment]
Hey,

deps are all up to date. Also tried the moduleMapper in the jest config without success. Any other ideas? 

node: v 16.8.0
"jest": "^27.1.0"
"nexus-prisma": "^0.33.0",
"nexus": "^1.1.0",

jest config in package.json
```
  "jest": {
    "setupFiles": [
      "dotenv/config"
    ],
    "setupFilesAfterEnv": [
      "./src/test/jest-setup.ts"
    ],
    "transform": {
      "\\.tsx?$": [
        "babel-jest",
        {
          "configFile": "./.babelrc.jest.js"
        }
      ]
    }
  },

```

**Comment by jasonkuhrt** [comment]
Can you share a repo repro?

**Comment by Manubi** [comment]
I would need to make one. Will you look into it if I make one? 😄

**Comment by jasonkuhrt** [comment]
@Manubi yep if its not massive 😅

**Comment by Manubi** [comment]
Sorry, didn't have time to make a repo repro. 
But, https://github.com/facebook/jest/issues/9771 looks like Jest has still problems with importing from `exports` in the package.json. Maybe an improvement would be his "[solution](https://github.com/facebook/jest/issues/9771#issuecomment-905222286)", and adding the resolver in the docs of nexus-prisma?

**Comment by sachinraja** [comment]
[`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import) is also erroring [`import/no-unresolved`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unresolved.md).

**Comment by jasonkuhrt** [comment]
We used to have the old system.

If I bring it back it seems that it will support old systems still transitioning to ESM

**Comment by jasonkuhrt** [comment]
I'm convinced to bring back the old system. Will try to push a fix for this soon. If someone wants to go in the git history and pull it back out into a new pr please do

**Comment by sachinraja** [comment]
Can't we just add a `scalars.js` that re-exports `dist-cjs/entrypoints/scalars.js` to the root dir?

**Comment by jasonkuhrt** [comment]
Yes this is what we used to do. Again just look in the git history. We had a script that built the facade files before publishing. We did not commit them to the repo.

**Comment by jasonkuhrt** [comment]
About .mjs I am waiting for TS to do this, it should land later this year.

**Comment by sachinraja** [comment]
> Yes this is what we used to do. Again just look in the git history. We had a script that built the facade files before publishing.

Oh sorry, I should have looked first.

> About .mjs I am waiting for TS to do this, it should land later this year.

Correct me if I'm wrong, but I don't think the TS team has plans for that looking at Microsoft/TypeScript#18442. The ESM files cannot be imported otherwise and `dist-esm` is useless. Also a simple rename wouldn't be too difficult `renamer -regex --find '\.js^' --replace '.mjs' './dist-esm/**/*.js'`. 

I understand if you don't want to do this though, just suggesting in case you do still want to have cjs and esm builds.

**Comment by jasonkuhrt** [comment]
> Correct me if I'm wrong, but I don't thin

I haven't followed that issue too closely, my plan was to wait for it to be closed and see what the outcome was.

**Comment by Manubi** [comment]
Hey,
jest added a resolver field in the latest version [v27.0.2 ](https://github.com/facebook/jest/releases)`. Does anyone know how that setup should look like in order to work with nexus-prisma? 😶‍🌫️  Because I think it should fix this problem. Correct?

**Comment by jasonkuhrt** [comment]
Hm!

**Comment by ZaniLuca** [comment]
Is this issue solved for everyone? I'm on `"nexus-prisma": "^0.35.0"`
And if  i try to run my tests with `jest` this is the output:
```bash
yarn run v1.22.10
$ yarn generate && jest
$ ts-node --transpile-only src/graphql/schema
 FAIL  tests/User.test.ts
  ● Test suite failed to run

    Cannot find module 'nexus-prisma/scalars' from 'src/graphql/schema.ts'

    Require stack:
      src/graphql/schema.ts
      src/index.ts
      tests/__helpers/testContexts.ts
      tests/User.test.ts

      2 | import * as types from "./definitions";
      3 | import { makeSchema } from "nexus";
    > 4 | import NexusPrismaScalars from "nexus-prisma/scalars";
        | ^
      5 |
      6 | export const schema = makeSchema({
      7 |   // `NexusPrismaScalars` is for supporting the `DateTime` type

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/graphql/schema.ts:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.724 s
Ran all test suites.
error Command failed with exit code 1.
```
