### ISSUE TITLE
Fix documentation links

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/nexus-prisma#138]
#### Perceived Problem

![CleanShot 2021-09-01 at 08 53 43@2x](https://user-images.githubusercontent.com/284476/131674769-dc4a2e31-68c4-44ed-bcb5-aa6de508b1cd.png)

#### Ideas / Proposed Solution(s)

- all anchor links that were used in the README need to be updated

**Comment by jasonkuhrt** [comment]
@iddan can you take care of this?

**Comment by iddan** [comment]
Will do
