### ISSUE TITLE
Doesn't work with ES modules

### ISSUE THREAD

**Issue by MikeYermolayev** [prisma/nexus-prisma#142]
Hello 👋🏻

As I can see #124 was implemented but I have some problems with it. When I try to import nexus-prisma it still tries to import cjs module so I get errors trying to run my app.

Any ideas? type is set to 'module' and nexus-prisma is imported using "import" keyword

![image](https://user-images.githubusercontent.com/8783498/131753149-00b61d9a-0a30-4b8f-9e92-3eeea79f367c.png)

EDIT: If I change import to
```
import nexusPrisma from 'nexus-prisma';

const {FuelStation} = nexusPrisma
```
then I get the following error:
```
(node:56355) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/Volumes/Workspace/pets/cheapoil/core/node_modules/nexus-prisma/dist-esm/entrypoints/main.js:1
import { inspect } from 'util';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

_Originally posted by @MikeYermolayev in https://github.com/prisma/nexus-prisma/discussions/141_

**Comment by jasonkuhrt** [comment]
If you share a repro repo it would help a lot.

**Comment by MikeYermolayev** [comment]
@jasonkuhrt here you go https://github.com/MikeYermolayev/nexus-prisma-es6-repro

If iI run `node src/index.js` I receive the above mentioned issue

![image](https://user-images.githubusercontent.com/8783498/134430972-d4072621-3d30-4e8a-b288-83e6e99c665f.png)

**Comment by MikeYermolayev** [comment]
Looks like the problem is in wrong build for esm. Imports inside esm should contain extensions but as I can see they don't.

I'll try to look into this during this week (Nov 17- Nov 21)

**Comment by MikeYermolayev** [comment]
Small update:

I can confirm that things start to work either when I change files extensions in dist-esm to `.mjs` or when I change "type" in package.json to "module" and set `.js` extension in imports.

So I suppose there are two possible solutions:

1. Use babel to generate dist-* folders with `.cjs` and `.mjs` extensions like in this article https://medium.com/dazn-tech/publishing-npm-packages-as-native-es-modules-41ffbc0a9dea
2. Change module type to ESM

@jasonkuhrt I can work on the solution but I'd like to know which of them is more preferable )

**Comment by jasonkuhrt** [comment]
@MikeYermolayev can we change module type to ESM while still supporting CJS?

A "clean" solution here might be to wait for TS to support outputing ESM compliant files and supporting .exports package json spec.

TS supporting won't only mean less work for us here but a sign that the community is maturing toward that direction.

I'm not keen on taking on bespoke complexity for this if its a tiny minority group of users.

But I'm open to discussing more at this point.

**Comment by P4sca1** [comment]
The easiest way to fix this would be to just rename the file extension for the ESM build to .mjs.

AFAIK, this is not supported by tsc, but you could switch to https://github.com/evanw/esbuild, which would also improve build times. I have an example repo for a package that supports both CJS and ESM: https://github.com/p4sca1/cron-schedule

Alternatively, a simple build script (or npm package), which renames the file extension after building might be sufficient.

**Comment by jasonkuhrt** [comment]
@P4sca1 I'll give esbuild and that repo a look. Is it truly a 100% drop in replacement? Would you be up for a PR?

**Comment by misha-erm** [comment]
Well, as I understand it's even doable with tsc alone. You will need to compile package with two different tsconfigs and fix `type` property in package.json in both `dist` folders. And the code should be written in esm manner. https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html 

But I like more the approach @P4sca1 suggested. Also [tsup](https://tsup.egoist.sh/#bundle-formats) tool might be worth trying. Seems pretty easy in usage and it's powered by esbuild. example: https://antfu.me/posts/publish-esm-and-cjs#tsup

**Comment by jasonkuhrt** [comment]
> The easiest way to fix this would be to just rename the file extension for the ESM build to .mjs.

IIUC it will also require updating internal import references. Shouldn't add too much effort though.

> and fix type property in package.json in both dist folders
I don't want a solution that relies on multiple emitted package.json fields.

I am OK to work with Node 12+ package `.exports`. It should be enough. Might be missing something though, the articles talks about issues with that. I believe my above point would address it but maybe not.

> Also tsup tool might be worth trying.

I looked briefly. It's a bundler. Why would we want to bundle ahead of time. To me bundling is a last step that should be handled by application projects before shipping to production.

**Comment by jasonkuhrt** [comment]
Am accepting PRs for this.

Personally waiting for TS to support package exports. Considering it was in beta in 4.5 maybe it won't be to long for it to land... 4.6? We'll see...

**Comment by sonofmagic** [comment]
ES modules is still not work. To use  `@apollo/server` , i have to change my `type` to `module`.
When i run my project, some error shown:
```
import { User } from 'nexus-prisma';
         ^^^^
SyntaxError: Named export 'User' not found. The requested module 'nexus-prisma' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'nexus-prisma';
const { User } = pkg;
```
And i make this change and restart, some error throw:
```
node_modules\.pnpm\nexus-prisma@1.0.4_63udwhd7sp4du2rzhags75opna\node_modules\nexus-prisma\dist-esm\entrypoints\main.js:1
import { inspect } from 'util';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

https://github.com/graphql-nexus/nexus-prisma/discussions/141

**Comment by peacechen** [comment]
The transpiled esm files have `.js` extensions instead of `.mjs`. This breaks builds because `.js` is process as CJS while `.mjs` is processed as ESM. The output files should name them with the `.mjs` suffix.

<img width="214" alt="Screen Shot 2023-05-11 at 12 22 04 AM" src="https://github.com/graphql-nexus/nexus-prisma/assets/6295083/6b7e655d-c45c-414a-8e73-c3a3975c16ee">
