### ISSUE TITLE
Unsing the next prisma best practice leads to error  "The GraphQL context.prisma value is not an instance of the Prisma Client"

### ISSUE THREAD

**Issue by tomsvogel** [prisma/nexus-prisma#146]
the link to the best practice => https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices

#### Screenshot

![image](https://user-images.githubusercontent.com/2229728/132854501-79026283-d68a-405d-bf6b-18976c3e29b9.png)

![image](https://user-images.githubusercontent.com/2229728/132854953-6b69096b-1df9-4d94-b083-0b8627801316.png)

it works fine if I use the Client directly.

**Comment by heddendorp** [comment]
Even without that I experience this issue when using fields that are 1:n relationships

**Comment by jasonkuhrt** [comment]
Here is what is happening:

1. NP makes a check that the PC value passed to context is an instance of the PC class.
2. The PC Class is imported from `@prisma/client`
3. During development with Vercel (maybe other tools too) its dev mode does weird things that require the above hack. Although that looks like a production time thing which I find confusing so maybe there is more I am missing, anyways.
4. The manual module caching and flushing going on in development seems to be leading to a case where the cached version of prisma (stored on global) is no longer linkable to the class found by importing it.

I might have a detail or two off here, but roughly I believe this is what is happening.

This is pretty annoying.

I think I might have to resort to duck typing to do the validation check.

Or else make it possible to disable.

Ideas welcome.

**Comment by tomsvogel** [comment]
Hello @jasonkuhrt, hello @heddendorp, 
we found an other solution that works fine for us. If you do not have some concerns in using that way, the issue could be closed and i will create a PR to prisma docs with the working solution.


`
import {PrismaClient} from '@prisma/client';

class DBClient {
  public prisma: PrismaClient;
  private static instance: DBClient;
  private constructor() {
    this.prisma = new PrismaClient();
  }

  public static getInstance = () => {
    if (!DBClient.instance) {
      DBClient.instance = new DBClient();
    }
    return DBClient.instance;
  };
}

export default DBClient;
`

**Comment by jasonkuhrt** [comment]
@tomsvogel that would be great. Can you come up with a version that does not create closures or use classes? Simplest thing possible is what I'm looking for is all.

**Comment by villesau** [comment]
I'm experiencing the same.

What about relaxing the check to null/undefined check only? I think the main purpose of the check is to validate that `prisma` is given in the context. It might be common to forget to pass it in the first place but probably fairly uncommon to pass something totally wrong altogether. Or does it really matter wether the `prisma` property is actually prisma instance? If similar interface is enough, there probably shouldn't be `instanceof` check, especially if it causes problems with next.js.

**Comment by villesau** [comment]
Alternatively, something like this could work as well if the check really check only active instances:

```
import { PrismaClient } from '@prisma/client'

declare global {
  var prisma: PrismaClient | undefined
}
const prismaClient = new PrismaClient({
  log: ['query'],
})

if (process.env.NODE_ENV !== 'production') {
  if(global.prisma) {
    global.prisma.$disconnect(); // <--- this might do the trick if the prisma instance counter is not too naíve
  }
  global.prisma = prismaClient
}

export const prisma = prismaClient;
```

It is derived from this: https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices#solution

**Comment by tomsvogel** [comment]
@jasonkuhrt @villesau, did you try the solution i posted above? We are using this in our code and works as expected.

**Comment by jasonkuhrt** [comment]
I'll try to take a look at this soon. I think there are some reasonable ideas in this thread :)

**Comment by ivanms1** [comment]
> Even without that I experience this issue when using fields that are 1:n relationships

This same thing happens to me as well :(

**Comment by tomsvogel** [comment]
@ivanms1 I had the same issues, but with my solution [here](https://github.com/prisma/nexus-prisma/issues/146#issuecomment-927573162) it works fine

**Comment by ivanms1** [comment]
@tomsvogel I made that change, but I needed an extra change that I just figured out now.
```js
const apollo = new ApolloServer({
  schema,
  context: () => {
    return {
      prisma, // before db: prisma,
    };
  },
});
```
And subsequently change everything from `ctx.db` to `ctx.prisma`, but that's ok.
Thank you for your solution.

**Comment by jasonkuhrt** [comment]
Here is my solution.

1. Keep an instance check around.
2. Add a new check layer based on duck typing.
3. If the instance check fails fall back to the duck type check.
4. If the duck type check fails throw an error.
5. If the duck type check succeeds then emit a warning that the instance check failed but its probably ok, though not ideal.
6. Add an option to disable the warning. Mention how to do this in the emitted warning.

	  ```ts
	  import { $settings } from 'nexus-prisma'
	  
	  $settings.change({
	    checks: {
	      prismaClientOnContext: false
	    }
	  })
	  ```

**Comment by villesau** [comment]
Could it be a setting for the generated client, something like:

```
generator nexusPrisma {
  provider      = "nexus-prisma"
  instanceCheck = false
}
```

Just a thought. Then there would not be need for global runtime settings.

**Comment by jasonkuhrt** [comment]
@villesau there are already global runtime settings. Gentime settings exist as well, but we avoid using Prisma schema to specify them because there is not enough tooling support to make a good experience there. Between Gentime and Runtime settings Runtime is preferred because it doesn't require an extra file to configure. Some things can only be achieved and Gentime and for those then use Gentime settings are used.

**Comment by jasonkuhrt** [comment]
The work took a bit longer than expected because of testing. In the end it forced and led to various positive refactoring anyways and tests are forever easier to work in in some regards now. Basically has to do with caching prisma client generate output per test. Also a bunch of general code health abstraction refreshes.

The end result is documented in JSDoc. It is too expensive for me to document this twice. I'm relying on paka.dev to provide the website version of readable docs for these settings.

I think there's room for improvement still, particularly in the JSDoc and error messages, but the thrust of this issue is well resolved at this point. New issues and feedback welcome. Thanks for bringing attention to this area all!

**Comment by garth** [comment]
Just tried the latest next branch with the duck type checking. It works, but we now get a warning on every api call. Would it be possible to only report the warning 1 time or have an option to disable the warning?

**Comment by jasonkuhrt** [comment]
@garth the warning can be disabled, check the gentime settings (or maybe its the runtime settings I forget right now).

**Comment by garth** [comment]
> @garth the warning can be disabled, check the gentime settings (or maybe its the runtime settings I forget right now).

Are there any docs or src files I should look at to find out how to do it?

**Comment by jasonkuhrt** [comment]
JSDoc should be complete. Once Paka is fixed they'll be available on the web as well. Not right now though.

**Comment by garth** [comment]
Finally figured it out (the typing for these settings is not picked up by VSCode, so you have to verify settings against the docs):

```ts
// turn off nexus context checks for prisma
import { $settings } from '~/nexus-prisma'
$settings({
  checks: {
    PrismaClientOnContext: false, // or process.env.NODE_ENV !== 'production'
  },
})
```

This is also required for production builds, since nexus-prisma doesn't turn off the ducktype checking for production.

**Comment by jasonkuhrt** [comment]
> Finally figured it out (the typing for these settings is not picked up by VSCode

Oh wow I would consider that a bug, issue welcome for this.

> since nexus-prisma doesn't turn off the ducktype checking for production.

We might do that in the future, for performance reasons etc.

Issue welcome for that too, I don't think I created one yet.

**Comment by villesau** [comment]
@jasonkuhrt Looks like the fix isn't published is it? Or how do I turn the check off? At least the 0.35.0 package does not seem to contain any mention about `PrismaClientOnContext` If I've understood correctly that it should be the setting to toggle.

I'm getting 

````
TS2345: Argument of type '{ checks: { PrismaClientOnContext: boolean; }; }' is not assignable to parameter of type 'UnwrapSyntheticLeavesDeeply<SettingsInput, true>'.   Object literal may only specify known properties, and 'checks' does not exist in type 'UnwrapSyntheticLeavesDeeply<SettingsInput, true>'.
```
