### ISSUE TITLE
Eslint can't resolve scalars

### ISSUE THREAD

**Issue by JulianKarhof** [prisma/nexus-prisma#150]
#### Screenshot
![image](https://user-images.githubusercontent.com/16868419/134220812-f295877c-2450-4855-937b-e9b0cf61dfe3.png)

#### Description
Whenever i try to import 'nexus-prisma/scalars' in any way, eslint marks it as an unresolved import:
`Unable to resolve path to module 'nexus-prisma/scalars'.`
I have never had these issues with any other imports and am confused as to what could be causing this.
I've done all basic troubleshooting steps like re-installing node_modules, re-generating nexus-prisma outputs and re-downloading the repo but nothing so far has been of any help.

Seems related to #137 , #124

**Comment by jasonkuhrt** [comment]
@JulianKarhof Are you on `0.34.x`?

**Comment by JulianKarhof** [comment]
The version was indeed `0.33.x`, upgrading to `0.34.x` has resolved the issue, thank you for your help!
