### ISSUE TITLE
TypeError: chalk_1.default.Instance is not a constructor

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/nexus-prisma#155]
#### Screenshot

<img width="1161" alt="Screenshot 2021-10-26 at 6 51 04 PM" src="https://user-images.githubusercontent.com/16436270/138887413-bb128bdf-6323-4cca-b3d0-ed2c33d8e947.png">

#### Description

I get this error often:

> TypeError: chalk_1.default.Instance is not a constructor

The complete error:

```
TypeError: chalk_1.default.Instance is not a constructor
    at Object.<anonymous> (~/twitter-api-v2-3-legged-login-using-next-connect/node_modules/@nexus/logger/src/chalk.ts:9:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (~/twitter-api-v2-3-legged-login-using-next-connect/node_modules/@nexus/logger/src/filter.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
```

I don't know what to make of it. I did perform `npm ls @nexus/logger` & I got the following:

```
twitter-api-v2-3-legged-login-using-next-connect
└─┬ nexus-prisma@0.34.0
  └─┬ setset@0.0.7
    └── @nexus/logger@0.2.0
```

which means it comes from `setset` which is dependency of `nexus-prisma`

#### Repro Steps/Link

I have a repro commit that will reproduce this error → https://github.com/deadcoder0904/twitter-api-v2-3-legged-login-using-next-connect/commit/b2bc0574eb6818f92cd7602afe823c70c096432c

Would love to know what this error is & what's causing it as I've seen it more than 10 times now?

**Comment by deadcoder0904** [comment]
Another simpler reproduction → https://github.com/deadcoder0904/codegen-error

**Comment by jasonkuhrt** [comment]
Thanks for the repro @deadcoder0904 

Can you remove the nextjs stuff, I don't think its needed.

I'll try to get this fixed soon.

**Comment by deadcoder0904** [comment]
> Can you remove the nextjs stuff, I don't think its needed.

What Next.js stuff? I basically start every project nowadays with Next.js by default since it's just 1-line of code & everything is ready-made for you.

**Comment by jasonkuhrt** [comment]
Anything to make the repro simpler/smaller the better. Deps, files, everything.

**Comment by jasonkuhrt** [comment]
I have simplified it a lot https://github.com/jasonkuhrt/codegen-error.

If I remove this dep and trigger a lock rebuild it fixes the issue https://github.com/jasonkuhrt/codegen-error/commit/9852704b78b9711cf36e9e890ad2cbbe11c95bff.

I don't understand the issue at this time. I believe the issue is somehow in the project. I've seen similar issues in our stacks and the issue is generally not at the library level.

If you can reproduce off my fork in a way that isn't about the lock file then please re-open.

**Comment by deadcoder0904** [comment]
yeah, i was confused whether it is in `graphql-codegen` or `nexus-prisma` under `setset`. i'll have to see that again but i'm currently using `nexus-plugin-prisma` again as i couldn't get `nexus-prisma` to work with my setup & i waited way too long.

i'll probably try `nexus-prisma` again when it's stable & re-open the issue if it still happens with my setup 👍

**Comment by khuezy** [comment]
I'm also having this issue using `0.35.0` with prisma `3.10.0`.

Downgrading to `nexus-prisma: 0.34.0` works.

The chalk error is coming from `floggy`
`node_modules/floggy/dist-cjs/chalk.js`
