### ISSUE TITLE
Support projecting enums

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/nexus-prisma#16]
#### Perceived Problem

It is currently not possible to project enums from Prisma schema into the the GraphQL API.

Example:

```prisma
enum ProjectRole {
  admin
  developer
  collaborator
  viewer
}
```

```ts
enumType({
  name: 'ProjectRole',
  members: ['admin', 'developer', 'collaborator', 'viewer'],
})
```

#### Ideas / Proposed Solution(s)

Generate representations of Prisma Schema enums.

```ts
import { ProjectRole } from 'nexus-prisma'

ProjectRole.name // 'ProjectRole'
ProjectRole.members // ['admin', 'developer', 'collaborator', 'viewer']

enumType(ProjectRole),
```

It might also be handy to have access to some of the individual pieces of data.

```ts
import { ProjectRole } from 'nexus-prisma/data'

ProjectRole.admin           // 'admin'
ProjectRole.developer       // 'developer'
ProjectRole.collaborator    // 'collaborator'
ProjectRole.viewer          // 'viewer'
```

Similarly it might be handy to have access to the types:

```ts
import type { ProjectRole } from 'nexus-prisma/types'

type a = ProjectRole.Admin           // 'admin'
type b = ProjectRole.Developer       // 'developer'
type c = ProjectRole.Collaborator    // 'collaborator'
type d = ProjectRole.Viewer          // 'viewer'

type z = ProjectRole.$Members        //  ProjectRole.Admin | ProjectRole.Developer | ProjectRole.Collaborator | ProjectRole.Viewer
```

**Comment by jasonkuhrt** [comment]
> It might also be handy to have access to some of the individual pieces of data.
> Similarly it might be handy to have access to the types:

Did not do this for now. Revisit once we have a concrete use-case.

**Comment by kidqueb** [comment]
This solution doesn't cover all use cases and lacks some features available in `enumType` but overall has been working out ok for me thus far. Figured I'd drop it here incase others come across this looking for a quick hacky fix.

```
import { Prisma } from ".prisma/client";
import { enumType } from "nexus";

export const enumTypes = Prisma.dmmf.datamodel.enums.map((e) => {
  return enumType({
    name: e.name,
    members: e.values,
  });
});

```

**Comment by jasonkuhrt** [comment]
@kidqueb what is missing? https://github.com/prisma/nexus-prisma#project-enums
