### ISSUE TITLE
Mapping prisma int id to graphql int scalar instead of ID scalar

### ISSUE THREAD

**Issue by ahmedosama7450** [prisma/nexus-prisma#22]
#### Perceived Problem
Currently, prisma ids (even integers) are mapped to graphql ID scalar which are mapped to typescript strings
This goes in conflict with prisma itself which maps ids into their corresponding type (int or string)

For example, If I am to return the result of a prisma query in a resolver, I will receive a type error because of that confilct which is what I am facing right now.
```
export const User = objectType({
  name: _User.$name,
  definition(t) {
    t.field(_User.id.name, User.id);
  },
});
```
```
export const UserQuery = queryField((t) => {
  t.nonNull.field("me", {
    type: "User",
    async resolve(_, __, { prisma, auth }) {
      const me = await prisma.user.findUnique({
        where: {
          id: auth!.userId,
        },
      });

      if (!me) {
        throw new AuthenticationError("You id does not exist in the database");
      }

      return me;
    },
  });
});
```

I receive this error
`Types of property 'id' are incompatible.
                    Type 'number' is not assignable to type 'MaybePromise<string>'`

As a workaround, I manually changed the type
```
export const User = objectType({
  name: _User.$name,
  definition(t) {
    t.field(_User.id.name, { type: "Int" });
  },
});
```
#### Ideas / Proposed Solution(s)
To go along with prisma typing, int ids should be mapped to graphql int scalar instead of the ID scalar

**Comment by P4sca1** [comment]
@lvauvillier @jasonkuhrt I still get `ID` scalars.
Im using `nexus-prisma` v0.30.0 and `prisma` v2.29.1.

**Comment by jasonkuhrt** [comment]
@P4sca1 have you tried https://github.com/prisma/nexus-prisma#reference-1

**Comment by P4sca1** [comment]
Opps, I forgot I set it to `'ID'`. My bad. Thanks for the quick help! :)
