### ISSUE TITLE
nexus-prisma generator gets stucked

### ISSUE THREAD

**Issue by IvanRodriCalleja** [prisma/nexus-prisma#30]
SO:  Windows 10 Pro
Prisma version: 2.22.1
nexus-prisma version: 0.25.0

I am trying to generate models with `nexus-prisma` generator using the `prisma generate` command but when i run it, the process get stuck:

![image](https://user-images.githubusercontent.com/22966198/117728318-97f76000-b1e9-11eb-9c84-15c14b37d5ec.png)

You can find the reproduction repo [here](https://github.com/IvanRodriCalleja/nexus-prisma-issue)

I noticed that if i change the generators order inside `schema.prisma` file from: 

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

generator nexusPrisma {
   provider = "nexus-prisma"
}

model User {
  id  String  @id
}
``` 

to

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator nexusPrisma {
   provider = "nexus-prisma"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id  String  @id
}
```

I got a different error in the `prisma generate` process:

![image](https://user-images.githubusercontent.com/22966198/117728803-371c5780-b1ea-11eb-9361-a7dec2f9ffca.png)

I am not sure if i am doing something wrong, is it a issue or a mistake?

**Comment by jasonkuhrt** [comment]
There were some recent fixes. Are you on the latest `@next` version of NP?

**Comment by jasonkuhrt** [comment]
Yep this is correct.

I still find this issue puzzling.

The feedback is not acceptable at all.

I wonder if any error would lead to this hanging effect.

I wonder if the issue is to do with Prisma generate system rather than nexus-Prisma.

I think we should keep this issue until we know more. 

I don't have a windows machine. If you can find out more info about what triggers the hanging effect that would be great.

**Comment by jasonkuhrt** [comment]
Going to reopen this for visibility.

CC @janpio wonder if we've seen anything like this elsewhere.

**Comment by janpio** [comment]
No, doesn't ring a bell. (We had some stuff in context with Docker containers and specific Linux kernels - but this sounds different)

A good debugging step would be to set `DEBUG=*` and run the command again - hopefully you get some additional output that tells you what might be happening.

**Comment by IvanRodriCalleja** [comment]
@janpio  I have to do it in the .env, right?

I added `DEBUG=*` to `prisma/.env` and logs are not logged in console when i run `prisma generate`, what i am doing wrong?

**Comment by jasonkuhrt** [comment]
@IvanRodriCalleja yeah that would, should, work.

I remember something about generators having this weird quirk that they swallow logs because they use stdout for a form of IPS or something... Maybe @Jolg42 can quickly confirm this.

**Comment by jasonkuhrt** [comment]
Please re-open if this is still an issue.

**Comment by jcbdev** [comment]
@jasonkuhrt  I have the same issue on m1 mac.

just freezes. Here are the logs with DEBUG=*

```
prisma:loadEnv project root found at /Users/tssc/Projects/tst1/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /Users/tssc/Projects/tst1/.env +0ms
Environment variables loaded from .env
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: /Users/tssc/Projects/tst1/node_modules/prisma/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getDMMF Using CLI Query Engine (Node-API) at: /Users/tssc/Projects/tst1/node_modules/prisma/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:generator prismaCLIDir /Users/tssc/Projects/tst1/node_modules/prisma +0ms
  prisma:generator prismaClientDir /Users/tssc/Projects/tst1/node_modules/@prisma/client +0ms
  prisma:generator baseDir /Users/tssc/Projects/tst1/prisma +0ms
  prisma:generator typescriptPath /Users/tssc/Projects/tst1/node_modules/typescript +1ms
  nexus-prisma found outputSourceDir /Users/tssc/Projects/tst1/node_modules/nexus-prisma/dist-esm/runtime +0ms
  nexus-prisma found outputSourceDir /Users/tssc/Projects/tst1/node_modules/nexus-prisma/dist-cjs/runtime +2ms
  prisma:GeneratorProcess 2022-01-27T00:44:18.721Z prisma:client:generator requiredEngine: libqueryEngine +0ms
  prisma:getGenerators neededVersions {
  "34df67547cf5598f5a6cd3eb45f14ee70c3fb86f": {
    "engines": [
      "libqueryEngine"
    ],
    "binaryTargets": []
  }
} +0ms
  prisma:getGenerators {
  prisma:getGenerators   generatorBinaryPaths: {
  prisma:getGenerators     libqueryEngine: {
  prisma:getGenerators       'darwin-arm64': '/Users/tssc/Projects/tst1/node_modules/prisma/libquery_engine-darwin-arm64.dylib.node'
  prisma:getGenerators     }
  prisma:getGenerators   }
  prisma:getGenerators } +46ms
  prisma:GeneratorProcess 2022-01-27T00:44:18.942Z prisma:loadEnv project root found at /Users/tssc/Projects/tst1/package.json +221ms
```
it never moves on from here.
