### ISSUE TITLE
Setup website for docs

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/nexus-prisma#33]
#### Perceived Problem

- README will not scale for the kind of detailed and verbose documentation that Nexus Prisma needs
- Many large code blocks needed to span the stack that Nexus Prisma sits across (db<>seed<>api<>client<>query<>json result)

#### Ideas / Proposed Solution(s)

- https://github.com/shuding/nextra
- https://github.com/remorses/dokz
- integrate with GH Pages
- Setup custom domain at https://nexus.prisma.io

**Comment by iddan** [comment]
How about (Docusaurus)[https://docusaurus.io/]?

**Comment by jasonkuhrt** [comment]
@iddan would prefer nextra or dokz, at least last I liked.
