### ISSUE TITLE
runtime `$settings` not exported from nexus-prisma

### ISSUE THREAD

**Issue by miralize** [prisma/nexus-prisma#57]
#### Screenshot
![image](https://user-images.githubusercontent.com/1761115/119246624-e823da00-bb7a-11eb-83da-d956ee815b30.png)

#### Description
Apologies if i'm missing something

Was seeing this error being thrown for a nested resolver
`'Prisma client not found in context. Set a Prisma client instance to 'prisma' field of Nexus context'`

Looking into it & after seeing the docs were updated to say you could customise the `prismaClientContextField` [using $settings](https://github.com/prisma/nexus-prisma#prismaclientcontextfield-string), but I'm seeing this error when trying 

![image](https://user-images.githubusercontent.com/1761115/119246579-93805f00-bb7a-11eb-8461-3f20c2dcd226.png)

Had a look into it & also noticed [this](https://github.com/prisma/nexus-prisma/blob/main/src/generator/models/javascript.ts#L173), should that also be `if (!ctx[settings.runtime.data.prismaClientContextField])` (once its configurable that is)?

**Comment by jasonkuhrt** [comment]
Available in 0.27.1

**Comment by miralize** [comment]
Thanks for the quick fix @jasonkuhrt ❤️ , looking forward to seeing the evolution of this lib :)
