### ISSUE TITLE
Add support for BigInt scalar

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/nexus-prisma#59]
#### Perceived Problem

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
- https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#bytes
- Not supported in our custom scalar support

#### Ideas / Proposed Solution(s)

- Use https://www.graphql-scalars.dev/docs/scalars/big-int
- Mention which Node version is needed to support this
- watch out for this:

  > In order to support BigInt in JSON.parse and JSON.stringify, it is recommended to install this npm package together with this scalar. Otherwise, JavaScript will serialize the value as string. json-bigint-patch

**Comment by iddan** [comment]
I think this can be unpinned
