### ISSUE TITLE
t.dateTime scalar helper not working

### ISSUE THREAD

**Issue by Zanibas** [prisma/nexus-prisma#63]
#### Description 
The t.dateTime scalar shorthand does not function as expected

#### Repro Steps/Link 
1) Installed the `NexusPrismaScalar` types in the types array for `makeSchema`
2) Attempted to write a definition for a field like:
```js
t.dateTime(User.createdAt.name, User.createdAt)
```
3) Received an error:
```
TSError: ⨯ Unable to compile TypeScript:
src/modules/User.ts:12:7 - error TS2339: Property 'dateTime' does not exist on type 'ObjectDefinitionBlock<"User">'.
```

However, there is a fix suggested on the Slack to use the long-form:
```js
t.field(User.createdAt.name, { type: 'DateTime', ...User.createdAt })
```
and this works.

Ideally, the scalar shorthand should work to avoid having to declare the type for each DateTime field.

Additionally, the documentation in the README is slightly off, the helper is `dateTime` instead of `datetime`.

**Comment by Zanibas** [comment]
I attempted to see if the issue could be fixed by not using the provided NexusPrismaScalar and instead a manually defined DateTime scalar, but both the methods in the nexus-prisma readme and on the nexus docs do not work. So, I'm inclined to believe there may be an issue there.

**Comment by jasonkuhrt** [comment]
> Additionally, the documentation in the README is slightly off, the helper is dateTime instead of datetime.

PR welcome!

**Comment by jasonkuhrt** [comment]
@Zanibas 

1. Did you ensure that Nexus reflection had run?
1. Can you please try the setup without using Nexus Prisma at all, and see if the error persists?

**Comment by Zanibas** [comment]
Whoops, found the issue--I was running a generate command before running ts-node dev, which looks like this:
```js
    "generate": "ts-node -r tsconfig-paths/register ./src/schema"
```
omitted the --transpile-only flag. Now it works! I'll submit a small PR for the README though.

**Comment by jasonkuhrt** [comment]
@Zanibas do you have an ideas about how this could have been less error prone?

Maybe the default Nexus Prisma implementation should log a warning to the terminal so that it becomes even more clear maybe... though given:

```ts
import { A, B, C } from 'nexus-prisma'
```

it will be a static error and not runnable so logging probably won't help much.

Any ideas?
