### ISSUE TITLE
DMMF dynamic require causing MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by haleksandre** [prisma/nexus-prisma#76]
#### Screenshot

![Screenshot from 2021-06-04 14-57-04](https://user-images.githubusercontent.com/8269937/120850591-a6fdd380-c545-11eb-8085-2dc2a833122a.png)

#### Description

`nexus-prisma` returns a "MODULE_NOT_FOUND" error when calling the function that fetches the DMMF.

It looks like the dynamic require here is throwing the error:

https://github.com/prisma/nexus-prisma/blob/acfdc6b08f84a0c752ec0edc8cc251c81302294f/src/helpers/prisma.ts#L14-L23

When I modify the variable `importId` for its default value '@prisma/client' directly in the require like so `require('@prisma/client')` it works correctly. So with that in mind I've tried a few "hack" such as trying to wrap the variable in a template literals ``require(`${importId}`)`` as well as appending an empty string `require('' + importId)` but both still returned the error. 

#### Possible solutions

Integrate the require code within the generated file /  generate the prisma helper file with the `require` pointing directly to the package name's string instead of using a variable at runtime?

Use dynamic `import` instead of `require`?

#### Repro Steps

https://github.com/haleksandre/nexus-prisma-test

```bash
git clone https://github.com/haleksandre/nexus-prisma-test.git
cd nexus-prisma-test

npm install
npm run build
node dist/server.js
```

**Comment by janpio** [comment]
What node version?
And the absolute folder being output is correct?

**Comment by haleksandre** [comment]
I've tried different version of node in the  12.x, 14.x & 16.x (I know 16.x isn't being tested yet but wanted to try) range within docker containers. 

#### 12.x

Will fail to build altogether because of a typing issue.

![Screenshot from 2021-06-05 10-37-46](https://user-images.githubusercontent.com/8269937/120895281-3b217680-c5ea-11eb-9654-586589a1da9d.png)

`NexusCore.ListDef<Post>` should technically be `NexusCore.NexusListDef<Post>`

#### 14.x & 16.x

Typing issue is still present but the build succeed & `./dist` folder is generated with all lthe files from `./src`

Then running `node dist/server.js`, in what ever node version (12.x, 14.x, 16.x) return the `MODULE_NOT_FOUND` error. The only way to make nexus-prisma find the package is by going into the `node_modules/nexus-prisma/dist/helpers/prisma.js` file explicitly put the string `'@prisma/client'` inside the require.

**Comment by haleksandre** [comment]
> I've tried different version of node in the 12.x, 14.x & 16.x (I know 16.x isn't being tested yet but wanted to try) within docker containers.
> 
> #### 12.x
> Will fail to build altogether because of a typing issue.
> 
> ![Screenshot from 2021-06-05 10-37-46](https://user-images.githubusercontent.com/8269937/120895281-3b217680-c5ea-11eb-9654-586589a1da9d.png)
> 
> `NexusCore.ListDef<Post>` should technically be `NexusCore.NexusListDef<Post>`
> 
> #### 14.x & 16.x
> Typing issue is still present but the build succeed & `./dist` folder is generated with all lthe files from `./src`
> 
> Then running `node dist/server.js`, in what ever node version (12.x, 14.x, 16.x) return the `MODULE_NOT_FOUND` error. The only way to make nexus-prisma find the package is by going into the `node_modules/nexus-prisma/dist/helpers/prisma.js` file explicitly put the string `'@prisma/client'` inside the require.

**Comment by haleksandre** [comment]
I fixed the issue & it was an issue on my side. Since I was running npm & node in seperate container with unknowly using different working directory for each. So the line below was outputting a different absolute path for `@prisma/client` in my npm container, while generating/building, that my node container couldn't find.

https://github.com/prisma/nexus-prisma/blob/c8b5f6cd644ae3fa077d5a1b1678e637fee4ae07/src/cli/nexus-prisma.ts#L35

**Comment by jasonkuhrt** [comment]
Going to keep this open as a better version of #79.

The thing I want to fix is this:

> On a side note, is there a reason prismaClientGenerator.output.value is generating an absolute path instead of passing a more flexible '@prisma/client' or relative paths?


You hit the issue on the head there @haleksandre, thanks!

**Comment by jasonkuhrt** [comment]
@haleksandre This is now fixed, or at least, a version of the problem.

If you can report back that would be great.

Thanks!

**Comment by haleksandre** [comment]
I've updated & haven't reencouter the issue.

Thanks @jasonkuhrt!
