### ISSUE TITLE
Always set `rejectOnNotFound` to false

### ISSUE THREAD

**Issue by jpulec** [prisma/nexus-prisma#98]
#### Description
It seems that there's some sort of interaction between setting `rejectOnNotFound: true` for `findUnique` globally and how nexus-prisma tries to resolve relations. Because nexus-prisma uses prisma's fluent API, it performs a `findUnique` for the parent model, and then tries to fetch the relation via the fluent API, which throws a `Not Found` error if the relation is null.

```prisma
// schema.prisma

model User {
  id @id
}

model Post {
   id @id
   userId  String? @map("user_id")
   user  User? @relation("user_id")
}
```

```typescript
import { objectType } from "nexus";

import { Post } from "nexus-prisma";

export const Post = objectType({
  name: "Post",
  definition(t) {
    t.nonNull.id("id");
    t.field(Post.user);
  }
});

```

```typescript
// lib/prisma.ts
import { PrismaClient } from "@prisma/client";

const  prisma = new PrismaClient({
  rejectOnNotFound: {
    findUnique: true,
  },
});
```

The above causes nexus-prisma to try to run `prisma.post.findUnique({ where: { id: <ID> } }).user()` which will throw a not found error if it is null.

Happy to provide any more explanation.

**Comment by P4sca1** [comment]
From my understanding, if you provide a nullable relation (like in this case `User?`), nexus should not throw when `post.user()` does not exist, but return null.
For this to work, `rejectOnNotFound: false` needs to be explicitly set to `false` for nullable relations using the fluent API, but NOT on the parent type (which seems to be not possible at the moment).

**Comment by jasonkuhrt** [comment]
Here's How I'm seeing the mapping:

```
(DB)                            (API)
Prisma                          GraphQL
------                          -------

nullable field relation     ->  nullable field relation

model A {                       type A {
  foo Foo?                        foo: Foo
}                               }

non-nullable field relation ->  non-nullable field relation

model A {                       type A {
  foo Foo                         foo: Foo!
}                               }

list field relation         ->  non-nullable list non-nullable field relation

model A {                       type A {
  foos Foo[]                      foo: [Foo!]!
}                               }
```

I think NP should ignore `rejectOnNotFound`. Ignoring means always having it set to `false` on queries it sends.

Does this make sense?

**Comment by jpulec** [comment]
I think that's probably a good start. Maybe it's worth making it configurable, but I think just always setting `rejectOnNotFound` to `false` would be better default behavior.

**Comment by jasonkuhrt** [comment]
I started the PR with updated docs. Feedback welcome https://github.com/prisma/nexus-prisma/tree/feat/reject-on-not-found-false#projecting-nullability.

**Comment by jasonkuhrt** [comment]
> Maybe it's worth making it configurable

Please bring a use-case in the future when you have one.

Also remember you can override the NP resolvers with your own logic fwiw.
