### ISSUE TITLE
Entity types cannot be resolved in PNPM monorepo

### ISSUE THREAD

**Issue by gurvan-guss** [prisma/nexus-prisma#99]
I'm having trouble running nexus-prisma in PNPM monorepo. I have two packages `users` & `posts`, when I run the command `prisma run generate`, `nexus-prisma` get resolved at the root directory instead of the package directory. Which causes entity types cannot be resolved as they got overwritten.

What should be expected is the generated output should be at the package node_modules level instead of the root directory, like `@prisma/client` in the screenshot below.

#### Screenshot
![image](https://user-images.githubusercontent.com/32047986/125159904-c9ba8200-e1ac-11eb-8528-606421b745e8.png)

It's a similar issue to this one for Prisma: https://github.com/prisma/prisma/issues/7484

**Comment by jasonkuhrt** [comment]
@millsp Are you saying the way `nexus-prisma` imports `@prisma/client` needs to change?

**Comment by jasonkuhrt** [comment]
@millsp in that example the output has been customized https://github.com/prisma/e2e-tests/blob/dev/packagers/pnpm-workspaces-custom-output/workspace/sub-project-2/prisma/schema.prisma#L3.

NP would use that as the import specifier.

So I see nothing new that NP needs to do.

**Comment by millsp** [comment]
Yep, custom output is the way to make it work with hoisted `node_modules`. Just need for @gurvan-guss to confirm if that worked.

**Comment by gurvan-guss** [comment]
Yes I confirm it worked by specifying a custom `output` :)
